project 'NewsListTest.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/facebook/flipper.git'
source 'https://github.com/CocoaPods/Specs'

swift_version = "4.1"

flipperkit_version = '0.19.0'


target 'NewsListTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NewsListTest
  platform :ios, '9.0'
  pod 'AFNetworking', '~>3.1.0'  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Test11
  pod 'FlipperKit', '~>' + flipperkit_version
  pod 'FlipperKit/FlipperKitLayoutComponentKitSupport', '~>' + flipperkit_version
  pod 'FlipperKit/SKIOSNetworkPlugin', '~>' + flipperkit_version
  pod 'FlipperKit/FlipperKitUserDefaultsPlugin', '~>' + flipperkit_version

  # This post_install script adds min deployment iOS version to yoga's pod target.
  # It also adds -DFB_SONARKIT_ENABLED=1 flag to OTHER_CFLAGS, necessary to build expose Flipper classes in the header files
  post_install do |installer|
      installer.pods_project.targets.each do |target|
               if ('Yoga' == target.name)
                   target.build_configurations.each do |config|
                     config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
                   end
               end
       end
        file_name = Dir.glob("*.xcodeproj")[0]
        app_project = Xcodeproj::Project.open(file_name)
        app_project.native_targets.each do |target|
            target.build_configurations.each do |config|
              if (config.build_settings['OTHER_CFLAGS'])
                if !(config.build_settings['OTHER_CFLAGS'].include? '-DFB_SONARKIT_ENABLED=1')
                  puts 'Adding -DFB_SONARKIT_ENABLED=1 in OTHER_CFLAGS...'
                  config.build_settings['OTHER_CFLAGS'] << '-DFB_SONARKIT_ENABLED=1'
                end
              else
                puts 'OTHER_CFLAGS does not exist, assigining it to `$(inherited), -DFB_SONARKIT_ENABLED=1` '
                config.build_settings['OTHER_CFLAGS'] = '$(inherited) -DFB_SONARKIT_ENABLED=1 '
              end
              app_project.save
            end
        end
   end
end
